trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection' # Replace with your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -X POST "https://cloudapi.cloud.couchbase.com/v4/organizations/42730eb3-53ab-451a-b5eb-8eeb9a92084c/projects/1f0721f9-6a58-4212-80b9-05d2e6a4d9e7/clusters" \
        -H "Authorization: Bearer ellHRXVvenkyckJQTDZXRjkxRnlmR3ZCbmJsZ3F3N0Y6a3FXM1NkU1ZtWk1pejM2eEZGSkRMYVNzajU4cnJJMWMwcjNiTUQ3WU1DIUQ4T2ZAWTd5QFJpUmNuazV2Y2ZYVw==" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "Test-Cluster-3",
          "description": "My first test Azure cluster.",
          "cloudProvider": {
            "type": "azure",
            "region": "westeurope",
            "cidr": "10.0.32.0/24"
          },
          "couchbaseServer": {
            "version": "7.6"
          },
          "serviceGroups": [
            {
              "node": {
                "compute": {
                  "cpu": 4,
                  "ram": 16
                },
                "disk": {
                  "type": "P6"
                }
              },
              "numOfNodes": 3,
              "services": [
                "data",
                "query",
                "index",
                "search"
              ]
            }
          ],
          "availability": {
            "type": "single"
          },
          "support": {
            "plan": "developer pro",
            "timezone": "GMT"
          }
        }'
